apiVersion: v1
kind: Ingress
metadata:
    name: patient-service-ingress
    namespace: default
    annotations:
        kubernetes.io/ingress.class: "nginx"
spec:
    rules:
    - host: patient-service.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patient-service
                port:
                  number: 8080