name: Build and Push Java Application Image to GCR
on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'Name of the application to build'
        required: true
        default: 'order-service'
        type: string
      GCP_Project:
        description: 'GCP Project ID'
        required: false
        default: 'project-4b8711e6-1e25-4675-ae6'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: '${{ inputs.application_name }}/pom.xml'

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ inputs.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set Application Directory
        run: |
          echo "APP_DIR=${{ inputs.application_name }}" >> $GITHUB_ENV
          cd $APP_DIR

      - name: Install Maven dependencies
        working-directory: ${{ inputs.application_name }}
        run: mvn clean package

      - name: Configure Docker to use gcloud credentials for GCR
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Docker Image to GCR
        run: |
          cd "$APP_DIR"
          APP_NAME="${{ inputs.application_name }}"
          if [ -z "$APP_NAME" ] || [ "$APP_NAME" = "." ]; then
            APP_NAME=$(basename "$PWD")
          fi
          IMAGE="asia-south1-docker.pkg.dev/${{ inputs.GCP_PROJECT }}/hackathon-repo/$APP_NAME:latest:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "Docker image pushed to $IMAGE"