name: Patient Service Build
on:
  workflow_dispatch:
jobs:
  build-nodejs:
    uses: ./.github/workflows/nodejs-build.yaml
    with:
      application_name: 'patient-service'
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}